# Generated by Django 5.1.2 on 2024-12-04 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
