# Generated by Django 5.1.2 on 2024-12-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_blog_featured_blog_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='verification_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
